/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AudioPackagesRouteImport } from './routes/audio_.packages'
import { Route as AuthProviderRouteImport } from './routes/auth/$provider'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as CampaignJoinRouteImport } from './routes/campaign/join'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as ApiAudioUploadsRouteImport } from './routes/api/audio/uploads'
import { Route as AudioPackagesPackageIdRouteImport } from './routes/audio_.packages_.$packageId'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth/callback/$provider'
import { Route as CampaignsCampaignIdEditRouteImport } from './routes/campaigns/$campaignId/edit'
import { Route as CampaignsCampaignIdPlayRouteImport } from './routes/campaigns/$campaignId/play'
import { Route as CampaignsCampaignIdSessionsRouteImport } from './routes/campaigns/$campaignId/sessions'
import { Route as CampaignsCampaignIdSoundboardRouteImport } from './routes/campaigns/$campaignId/soundboard'
import { Route as ApiAudioUploadsIdConfirmRouteImport } from './routes/api/audio/uploads.$id.confirm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioPackagesRoute = AudioPackagesRouteImport.update({
  id: '/audio_/packages',
  path: '/audio/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderRoute = AuthProviderRouteImport.update({
  id: '/auth/$provider',
  path: '/auth/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignJoinRoute = CampaignJoinRouteImport.update({
  id: '/campaign/join',
  path: '/campaign/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioUploadsRoute = ApiAudioUploadsRouteImport.update({
  id: '/api/audio/uploads',
  path: '/api/audio/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioPackagesPackageIdRoute = AudioPackagesPackageIdRouteImport.update({
  id: '/audio_/packages_/$packageId',
  path: '/audio/packages/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdEditRoute = CampaignsCampaignIdEditRouteImport.update({
  id: '/campaigns/$campaignId/edit',
  path: '/campaigns/$campaignId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdPlayRoute = CampaignsCampaignIdPlayRouteImport.update({
  id: '/campaigns/$campaignId/play',
  path: '/campaigns/$campaignId/play',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdSessionsRoute =
  CampaignsCampaignIdSessionsRouteImport.update({
    id: '/campaigns/$campaignId/sessions',
    path: '/campaigns/$campaignId/sessions',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignIdSoundboardRoute =
  CampaignsCampaignIdSoundboardRouteImport.update({
    id: '/campaigns/$campaignId/soundboard',
    path: '/campaigns/$campaignId/soundboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAudioUploadsIdConfirmRoute =
  ApiAudioUploadsIdConfirmRouteImport.update({
    id: '/$id/confirm',
    path: '/$id/confirm',
    getParentRoute: () => ApiAudioUploadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/dashboard': typeof DashboardRoute
  '/healthz': typeof HealthzRoute
  '/privacy': typeof PrivacyRoute
  '/readyz': typeof ReadyzRoute
  '/terms': typeof TermsRoute
  '/audio/packages': typeof AudioPackagesRoute
  '/auth/$provider': typeof AuthProviderRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/campaign/join': typeof CampaignJoinRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/audio/uploads': typeof ApiAudioUploadsRouteWithChildren
  '/audio/packages/$packageId': typeof AudioPackagesPackageIdRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/play': typeof CampaignsCampaignIdPlayRoute
  '/campaigns/$campaignId/sessions': typeof CampaignsCampaignIdSessionsRoute
  '/campaigns/$campaignId/soundboard': typeof CampaignsCampaignIdSoundboardRoute
  '/api/audio/uploads/$id/confirm': typeof ApiAudioUploadsIdConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/dashboard': typeof DashboardRoute
  '/healthz': typeof HealthzRoute
  '/privacy': typeof PrivacyRoute
  '/readyz': typeof ReadyzRoute
  '/terms': typeof TermsRoute
  '/audio/packages': typeof AudioPackagesRoute
  '/auth/$provider': typeof AuthProviderRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/campaign/join': typeof CampaignJoinRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/api/audio/uploads': typeof ApiAudioUploadsRouteWithChildren
  '/audio/packages/$packageId': typeof AudioPackagesPackageIdRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/play': typeof CampaignsCampaignIdPlayRoute
  '/campaigns/$campaignId/sessions': typeof CampaignsCampaignIdSessionsRoute
  '/campaigns/$campaignId/soundboard': typeof CampaignsCampaignIdSoundboardRoute
  '/api/audio/uploads/$id/confirm': typeof ApiAudioUploadsIdConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/dashboard': typeof DashboardRoute
  '/healthz': typeof HealthzRoute
  '/privacy': typeof PrivacyRoute
  '/readyz': typeof ReadyzRoute
  '/terms': typeof TermsRoute
  '/audio_/packages': typeof AudioPackagesRoute
  '/auth/$provider': typeof AuthProviderRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/campaign/join': typeof CampaignJoinRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/api/audio/uploads': typeof ApiAudioUploadsRouteWithChildren
  '/audio_/packages_/$packageId': typeof AudioPackagesPackageIdRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/play': typeof CampaignsCampaignIdPlayRoute
  '/campaigns/$campaignId/sessions': typeof CampaignsCampaignIdSessionsRoute
  '/campaigns/$campaignId/soundboard': typeof CampaignsCampaignIdSoundboardRoute
  '/api/audio/uploads/$id/confirm': typeof ApiAudioUploadsIdConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio'
    | '/dashboard'
    | '/healthz'
    | '/privacy'
    | '/readyz'
    | '/terms'
    | '/audio/packages'
    | '/auth/$provider'
    | '/auth/logout'
    | '/campaign/join'
    | '/campaigns/new'
    | '/campaigns/'
    | '/api/audio/uploads'
    | '/audio/packages/$packageId'
    | '/auth/callback/$provider'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/play'
    | '/campaigns/$campaignId/sessions'
    | '/campaigns/$campaignId/soundboard'
    | '/api/audio/uploads/$id/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio'
    | '/dashboard'
    | '/healthz'
    | '/privacy'
    | '/readyz'
    | '/terms'
    | '/audio/packages'
    | '/auth/$provider'
    | '/auth/logout'
    | '/campaign/join'
    | '/campaigns/new'
    | '/campaigns'
    | '/api/audio/uploads'
    | '/audio/packages/$packageId'
    | '/auth/callback/$provider'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/play'
    | '/campaigns/$campaignId/sessions'
    | '/campaigns/$campaignId/soundboard'
    | '/api/audio/uploads/$id/confirm'
  id:
    | '__root__'
    | '/'
    | '/audio'
    | '/dashboard'
    | '/healthz'
    | '/privacy'
    | '/readyz'
    | '/terms'
    | '/audio_/packages'
    | '/auth/$provider'
    | '/auth/logout'
    | '/campaign/join'
    | '/campaigns/new'
    | '/campaigns/'
    | '/api/audio/uploads'
    | '/audio_/packages_/$packageId'
    | '/auth/callback/$provider'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/play'
    | '/campaigns/$campaignId/sessions'
    | '/campaigns/$campaignId/soundboard'
    | '/api/audio/uploads/$id/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  DashboardRoute: typeof DashboardRoute
  HealthzRoute: typeof HealthzRoute
  PrivacyRoute: typeof PrivacyRoute
  ReadyzRoute: typeof ReadyzRoute
  TermsRoute: typeof TermsRoute
  AudioPackagesRoute: typeof AudioPackagesRoute
  AuthProviderRoute: typeof AuthProviderRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  CampaignJoinRoute: typeof CampaignJoinRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  ApiAudioUploadsRoute: typeof ApiAudioUploadsRouteWithChildren
  AudioPackagesPackageIdRoute: typeof AudioPackagesPackageIdRoute
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
  CampaignsCampaignIdEditRoute: typeof CampaignsCampaignIdEditRoute
  CampaignsCampaignIdPlayRoute: typeof CampaignsCampaignIdPlayRoute
  CampaignsCampaignIdSessionsRoute: typeof CampaignsCampaignIdSessionsRoute
  CampaignsCampaignIdSoundboardRoute: typeof CampaignsCampaignIdSoundboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio_/packages': {
      id: '/audio_/packages'
      path: '/audio/packages'
      fullPath: '/audio/packages'
      preLoaderRoute: typeof AudioPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$provider': {
      id: '/auth/$provider'
      path: '/auth/$provider'
      fullPath: '/auth/$provider'
      preLoaderRoute: typeof AuthProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/join': {
      id: '/campaign/join'
      path: '/campaign/join'
      fullPath: '/campaign/join'
      preLoaderRoute: typeof CampaignJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/uploads': {
      id: '/api/audio/uploads'
      path: '/api/audio/uploads'
      fullPath: '/api/audio/uploads'
      preLoaderRoute: typeof ApiAudioUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio_/packages_/$packageId': {
      id: '/audio_/packages_/$packageId'
      path: '/audio/packages/$packageId'
      fullPath: '/audio/packages/$packageId'
      preLoaderRoute: typeof AudioPackagesPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/edit': {
      id: '/campaigns/$campaignId/edit'
      path: '/campaigns/$campaignId/edit'
      fullPath: '/campaigns/$campaignId/edit'
      preLoaderRoute: typeof CampaignsCampaignIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/play': {
      id: '/campaigns/$campaignId/play'
      path: '/campaigns/$campaignId/play'
      fullPath: '/campaigns/$campaignId/play'
      preLoaderRoute: typeof CampaignsCampaignIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/sessions': {
      id: '/campaigns/$campaignId/sessions'
      path: '/campaigns/$campaignId/sessions'
      fullPath: '/campaigns/$campaignId/sessions'
      preLoaderRoute: typeof CampaignsCampaignIdSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/soundboard': {
      id: '/campaigns/$campaignId/soundboard'
      path: '/campaigns/$campaignId/soundboard'
      fullPath: '/campaigns/$campaignId/soundboard'
      preLoaderRoute: typeof CampaignsCampaignIdSoundboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/uploads/$id/confirm': {
      id: '/api/audio/uploads/$id/confirm'
      path: '/$id/confirm'
      fullPath: '/api/audio/uploads/$id/confirm'
      preLoaderRoute: typeof ApiAudioUploadsIdConfirmRouteImport
      parentRoute: typeof ApiAudioUploadsRoute
    }
  }
}

interface ApiAudioUploadsRouteChildren {
  ApiAudioUploadsIdConfirmRoute: typeof ApiAudioUploadsIdConfirmRoute
}

const ApiAudioUploadsRouteChildren: ApiAudioUploadsRouteChildren = {
  ApiAudioUploadsIdConfirmRoute: ApiAudioUploadsIdConfirmRoute,
}

const ApiAudioUploadsRouteWithChildren = ApiAudioUploadsRoute._addFileChildren(
  ApiAudioUploadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  DashboardRoute: DashboardRoute,
  HealthzRoute: HealthzRoute,
  PrivacyRoute: PrivacyRoute,
  ReadyzRoute: ReadyzRoute,
  TermsRoute: TermsRoute,
  AudioPackagesRoute: AudioPackagesRoute,
  AuthProviderRoute: AuthProviderRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  CampaignJoinRoute: CampaignJoinRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  ApiAudioUploadsRoute: ApiAudioUploadsRouteWithChildren,
  AudioPackagesPackageIdRoute: AudioPackagesPackageIdRoute,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
  CampaignsCampaignIdEditRoute: CampaignsCampaignIdEditRoute,
  CampaignsCampaignIdPlayRoute: CampaignsCampaignIdPlayRoute,
  CampaignsCampaignIdSessionsRoute: CampaignsCampaignIdSessionsRoute,
  CampaignsCampaignIdSoundboardRoute: CampaignsCampaignIdSoundboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
