/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as CampaignsNewRouteImport } from './routes/campaigns/new'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthProviderRouteImport } from './routes/auth/$provider'
import { Route as CampaignsCampaignIdSummaryRouteImport } from './routes/campaigns/$campaignId/summary'
import { Route as CampaignsCampaignIdEditRouteImport } from './routes/campaigns/$campaignId/edit'
import { Route as AuthCallbackProviderRouteImport } from './routes/auth/callback/$provider'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderRoute = AuthProviderRouteImport.update({
  id: '/auth/$provider',
  path: '/auth/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdSummaryRoute =
  CampaignsCampaignIdSummaryRouteImport.update({
    id: '/campaigns/$campaignId/summary',
    path: '/campaigns/$campaignId/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const CampaignsCampaignIdEditRoute = CampaignsCampaignIdEditRouteImport.update({
  id: '/campaigns/$campaignId/edit',
  path: '/campaigns/$campaignId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackProviderRoute = AuthCallbackProviderRouteImport.update({
  id: '/auth/callback/$provider',
  path: '/auth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
  '/auth/$provider': typeof AuthProviderRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/summary': typeof CampaignsCampaignIdSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
  '/auth/$provider': typeof AuthProviderRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/summary': typeof CampaignsCampaignIdSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/terms': typeof TermsRoute
  '/privacy': typeof PrivacyRoute
  '/auth/$provider': typeof AuthProviderRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/auth/callback/$provider': typeof AuthCallbackProviderRoute
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/summary': typeof CampaignsCampaignIdSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/terms'
    | '/privacy'
    | '/auth/$provider'
    | '/auth/logout'
    | '/campaigns/new'
    | '/campaigns/'
    | '/auth/callback/$provider'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/terms'
    | '/privacy'
    | '/auth/$provider'
    | '/auth/logout'
    | '/campaigns/new'
    | '/campaigns'
    | '/auth/callback/$provider'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/summary'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/terms'
    | '/privacy'
    | '/auth/$provider'
    | '/auth/logout'
    | '/campaigns/new'
    | '/campaigns/'
    | '/auth/callback/$provider'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TermsRoute: typeof TermsRoute
  PrivacyRoute: typeof PrivacyRoute
  AuthProviderRoute: typeof AuthProviderRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  AuthCallbackProviderRoute: typeof AuthCallbackProviderRoute
  CampaignsCampaignIdEditRoute: typeof CampaignsCampaignIdEditRoute
  CampaignsCampaignIdSummaryRoute: typeof CampaignsCampaignIdSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$provider': {
      id: '/auth/$provider'
      path: '/auth/$provider'
      fullPath: '/auth/$provider'
      preLoaderRoute: typeof AuthProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/summary': {
      id: '/campaigns/$campaignId/summary'
      path: '/campaigns/$campaignId/summary'
      fullPath: '/campaigns/$campaignId/summary'
      preLoaderRoute: typeof CampaignsCampaignIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/edit': {
      id: '/campaigns/$campaignId/edit'
      path: '/campaigns/$campaignId/edit'
      fullPath: '/campaigns/$campaignId/edit'
      preLoaderRoute: typeof CampaignsCampaignIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/$provider': {
      id: '/auth/callback/$provider'
      path: '/auth/callback/$provider'
      fullPath: '/auth/callback/$provider'
      preLoaderRoute: typeof AuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TermsRoute: TermsRoute,
  PrivacyRoute: PrivacyRoute,
  AuthProviderRoute: AuthProviderRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  AuthCallbackProviderRoute: AuthCallbackProviderRoute,
  CampaignsCampaignIdEditRoute: CampaignsCampaignIdEditRoute,
  CampaignsCampaignIdSummaryRoute: CampaignsCampaignIdSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
